#!/bin/bash
#
#SBATCH --job-name=plati20_process
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=6:00:00
#SBATCH --mem=6GB

module purge

singularity exec \
            --overlay ~/conda_envs/pytorch1.9-cuda102-15GB-500K.ext3:ro \
            /scratch/work/public/singularity/cuda10.2-cudnn8-devel-ubuntu18.04.sif \
            bash -c "source /ext3/env.sh; export PYTHONPATH=/scratch/sx801/scripts/physnet-dimenet/dataProviders:../../Design-16-uncertainty/; python plati20_process.py "
