#!/bin/bash
#
#SBATCH --job-name=csd20_process
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=6:00:00
#SBATCH --mem=6GB

module purge

singularity exec \
            --overlay ~/conda_envs/dnn-3.7-pytorch1.7.0-cuda11.0.ext3:ro /scratch/work/public/singularity/cuda11.0-cudnn8-devel-ubuntu18.04.sif \
            bash -c "source /ext3/env.sh; export PYTHONPATH=/scratch/sx801/scripts/physnet-dimenet/dataProviders:../../Design-16-uncertainty/; python csd20_process.py "
